import type { AllergyOption, CuisineOption, DietOption, DishTypeOption, MealTypeOption, NutrientCode, NutrientOption } from "../types";

// Note: Commented-out lines represent values that are currently present in Edamam Recipe Search documentation, but non-functional in the API

export const allergyOptions: AllergyOption[] = [
  {parameter: 'health', value: 'celery-free', label: 'Celery-free', definition: "Does not contain celery or derivatives"},
  {parameter: 'health', value: 'crustacean-free', label: 'Crustacean-free', definition: "Does not contain crustaceans (shrimp, lobster etc.) or derivatives"},
  {parameter: 'health', value: 'dairy-free', label: 'Dairy-free', definition: "No dairy; no lactose"},
  {parameter: 'health', value: 'egg-free', label: 'Egg-free', definition: "No eggs or products containing eggs"},
  {parameter: 'health', value: 'fish-free', label: 'Fish-free', definition: "No fish or fish derivatives"},
  {parameter: 'health', value: 'gluten-free', label: 'Gluten-free', definition: "No ingredients containing gluten"},
  {parameter: 'health', value: 'lupine-free', label: 'Lupine-free', definition: "Does not contain lupine (a legume) or its derivatives"},
  {parameter: 'health', value: 'mollusk-free', label: 'Mollusc-free', definition: "No molluscs, including clams, mussels, oysters, scallops, squid, octopus, snails, and more"},
  {parameter: 'health', value: 'mustard-free', label: 'Mustard-free', definition: "Does not contain mustard or derivatives"},
  {parameter: 'health', value: 'peanut-free', label: 'Peanut-free', definition: "No peanuts or products containing peanuts"},
  {parameter: 'health', value: 'sesame-free', label: 'Sesame-free', definition: "Does not contain sesame seed or derivatives"},
  {parameter: 'health', value: 'shellfish-free', label: 'Shellfish-free', definition: "No shellfish or shellfish derivatives"},
  {parameter: 'health', value: 'soy-free', label: 'Soy-free', definition: "No soy or products containing soy"},
  {parameter: 'health', value: 'sulfite-free', label: 'Sulfite-free', definition: "No sulfites"},
  {parameter: 'health', value: 'tree-nut-free', label: 'Tree-Nut-free', definition: "No tree nuts or products containing tree nuts"},
  {parameter: 'health', value: 'wheat-free', label: 'Wheat-free', definition: "No wheat, but can still contain gluten"}
];

export const cuisineOptions: CuisineOption[] = [
  {parameter: 'cuisineType', value: 'american', label: 'American'},
  {parameter: 'cuisineType', value: 'asian', label: 'Asian'},
  {parameter: 'cuisineType', value: 'british', label: 'British'},
  {parameter: 'cuisineType', value: 'caribbean', label: 'Caribbean'},
  {parameter: 'cuisineType', value: 'central europe', label: 'Central Europe'},
  {parameter: 'cuisineType', value: 'chinese', label: 'Chinese'},
  {parameter: 'cuisineType', value: 'eastern europe', label: 'Eastern Europe'},
  {parameter: 'cuisineType', value: 'french', label: 'French'},
  {parameter: 'cuisineType', value: 'greek', label: 'Greek'},
  {parameter: 'cuisineType', value: 'indian', label: 'Indian'},
  {parameter: 'cuisineType', value: 'italian', label: 'Italian'},
  {parameter: 'cuisineType', value: 'japanese', label: 'Japanese'},
  {parameter: 'cuisineType', value: 'korean', label: 'Korean'},
  {parameter: 'cuisineType', value: 'kosher', label: 'Kosher'},
  {parameter: 'cuisineType', value: 'mediterranean', label: 'Mediterranean'},
  {parameter: 'cuisineType', value: 'mexican', label: 'Mexican'},
  {parameter: 'cuisineType', value: 'middle eastern', label: 'Middle-Eastern'},
  {parameter: 'cuisineType', value: 'nordic', label: 'Nordic'},
  {parameter: 'cuisineType', value: 'south american', label: 'South American'},
  {parameter: 'cuisineType', value: 'south east asian', label: 'Southeast Asian'},
  {parameter: 'cuisineType', value: 'world', label: 'World'},
];

export const dietOptions: DietOption[] = [
  {parameter: 'health', value: 'alcohol-free', label: 'Alcohol-free', definition: "No alcohol used or contained"},
  {parameter: 'health', value: 'DASH', label: 'Anti-hypertensive', definition: "Dietary Approaches to Stop Hypertension diet"},
  {parameter: 'diet', value: 'balanced', label: 'Balanced', definition: "Protein/Fat/Carb values in 15/35/50 ratio"},
  {parameter: 'health', value: 'fodmap-free', label: 'FODMAP-free', definition: "Does not contain FODMAP foods, which cause digestive discomfort in some people"},
  {parameter: 'diet', value: 'high-fiber', label: 'High-Fiber', definition: "More than 5g fiber per serving"},
  {parameter: 'diet', value: 'high-protein', label: 'High-Protein', definition: "More than 50% of total calories from proteins"},
  {parameter: 'health', value: 'immuno-supportive', label: 'Immune Support', definition: "Recipes which fit a science-based approach to eating to strengthen the immune system"},
  {parameter: 'health', value: 'keto-friendly', label: 'Keto', definition: "Maximum 7 grams of net carbs per serving"},
  {parameter: 'health', value: 'kidney-friendly', label: 'Kidney-Friendly', definition: "Per serving: phosphorus less than 250 mg AND potassium less than 500 mg AND sodium less than 500 mg"},
  {parameter: 'health', value: 'kosher', label: 'Kosher', definition: "Contains only ingredients allowed by the kosher diet, although it does not guarantee kosher preparation of the ingredients themselves"},
  {parameter: 'diet', value: 'low-carb', label: 'Low-Carb', definition: "Less than 20% of total calories from carbs"},
  {parameter: 'diet', value: 'low-fat', label: 'Low-Fat', definition: "Less than 15% of total calories from fat"},
  {parameter: 'health', value: 'low-potassium', label: 'Low-Potassium', definition: "Less than 150mg per serving"},
  {parameter: 'diet', value: 'low-sodium', label: 'Low-Sodium', definition: "Less than 140mg sodium per serving"},
  {parameter: 'health', value: 'low-sugar', label: 'Low-Sugar', definition: "No simple sugars: glucose, dextrose, galactose, fructose, sucrose, lactose, or maltose"},
  {parameter: 'health', value: 'Mediterranean', label: 'Mediterranean', definition: "The Mediterranean Diet emphasizes plant-based foods and healthy fats"},
  {parameter: 'health', value: 'no-oil-added', label: 'No-Oil-Added', definition: "No oil added except for what is contained in the basic ingredients"},
  {parameter: 'health', value: 'paleo', label: 'Paleo', definition: "Excludes what are perceived to be agricultural products; grains, legumes, dairy products, potatoes, refined salt, refined sugar, and processed oils"},
  {parameter: 'health', value: 'pescatarian', label: 'Pescatarian', definition: "Does not contain meat or meat based products, can contain dairy and fish"},
  {parameter: 'health', value: 'pork-free', label: 'Pork-free', definition: "Does not contain pork or derivatives"},
  {parameter: 'health', value: 'red-meat-free', label: 'Red-Meat-free', definition: "Does not contain beef, lamb, pork, duck, goose, game, horse, and other types of red meat or products containing red meat"},
  {parameter: 'health', value: 'sugar-conscious', label: 'Sugar-Conscious', definition: "Less than 4g of sugar per serving"},
  {parameter: 'health', value: 'vegan', label: 'Vegan', definition: "No meat, poultry, fish, dairy, eggs or honey"},
  {parameter: 'health', value: 'vegetarian', label: 'Vegetarian', definition: "No meat, poultry, or fish"}
];

export const dishTypeOptions: DishTypeOption[] = [
  {parameter: 'dishType', value: 'bread', label: 'Bread'},
  {parameter: 'dishType', value: 'cereals', label: 'Cereals'},
  {parameter: 'dishType', value: 'alcohol cocktail', label: 'Cocktail'},
  {parameter: 'dishType', value: 'biscuits and cookies', label: 'Cookies'},
  {parameter: 'dishType', value: 'desserts', label: 'Dessert'},
  {parameter: 'dishType', value: 'drinks', label: 'Drinks'},
  {parameter: 'dishType', value: 'egg', label: 'Egg'},
  //{parameter: 'dishType', value: 'ice cream and custard', label: 'Ice Cream'},
  {parameter: 'dishType', value: 'main course', label: 'Main Course'},
  {parameter: 'dishType', value: 'pancake', label: 'Pancake'},
  {parameter: 'dishType', value: 'pasta', label: 'Pasta'},
  //{parameter: 'dishType', value: 'pastry', label: 'Pastry'},
  //{parameter: 'dishType', value: 'pies and tarts', label: 'Pies and Tarts'},
  //{parameter: 'dishType', value: 'pizza', label: 'Pizza'},
  {parameter: 'dishType', value: 'preps', label: 'Preps'},
  {parameter: 'dishType', value: 'preserve', label: 'Preserves'},
  {parameter: 'dishType', value: 'salad', label: 'Salad'},
  {parameter: 'dishType', value: 'sandwiches', label: 'Sandwiches'},
  {parameter: 'dishType', value: 'condiments and sauces', label: 'Sauces'},
  //{parameter: 'dishType', value: 'seafood', label: 'Seafood'},
  //{parameter: 'dishType', value: 'side dish', label: 'Side Dish'},
  {parameter: 'dishType', value: 'soup', label: 'Soup'},
  {parameter: 'dishType', value: 'special occasions', label: 'Special Occasions'},
  {parameter: 'dishType', value: 'starter', label: 'Starter'},
  //{parameter: 'dishType', value: 'sweets', label: 'Sweets'},
];

export const mealTypeOptions: MealTypeOption[] = [
    {parameter: 'mealType', value: 'breakfast', label:'Breakfast'},
    {parameter: 'mealType', value: 'brunch', label:'Brunch'},
    {parameter: 'mealType', value: 'lunch/dinner', label:'Lunch or dinner'},
    {parameter: 'mealType', value: 'snack', label:'Snack'},
    {parameter: 'mealType', value: 'teatime', label:'Teatime'}
];

export const nutrientOptions: NutrientOption[] = [
  {parameter: 'CA', label: 'Calcium', unit: 'mg', group: 'minerals'},
  {parameter: 'CHOCDF', label: 'Carbs, net', unit: 'g', group: "macros"},
  {parameter: 'CHOCDF.net', label: 'Carbs, total', unit: 'g', group: "macros"},
  {parameter: 'CHOLE', label: 'Cholesterol', unit: 'mg', group: "other"},
  {parameter: 'FAMS', label: 'Fat, monounsaturated', unit: 'g', group: "macros"},
  {parameter: 'FAPU', label: 'Fat, polyunsaturated', unit: 'g', group: "macros"},
  {parameter: 'FASAT', label: 'Fat, saturated', unit: 'g', group: "macros"},
  {parameter: 'FAT', label: 'Fat, total', unit: 'g', group: "macros"},
  {parameter: 'FATRN', label: 'Fat, trans', unit: 'g', group: "macros"},
  {parameter: 'FIBTG', label: 'Fiber', unit: 'g', group: "other"},
  {parameter: 'FOLDFE', label: 'Folate, DFE', unit: 'µg', group: "vitamins"},
  //{parameter: 'FOLFE', label: 'Folate, food', unit: 'µg', group: "vitamins"},
  {parameter: 'FOLAC', label: 'Folic acid', unit: 'µg', group: "vitamins"},
  {parameter: 'FE', label: 'Iron', unit: 'mg', group: 'minerals'},
  {parameter: 'MG', label: 'Magnesium', unit: 'mg', group: 'minerals'},
  {parameter: 'NIA', label: 'Niacin', unit: 'mg', group: "vitamins"},
  {parameter: 'P', label: 'Phosphorus', unit: 'mg', group: 'minerals'},
  {parameter: 'K', label: 'Potassium', unit: 'mg', group: 'minerals'},
  {parameter: 'PROCNT', label: 'Protein', unit: 'g', group: "macros"},
  {parameter: 'RIBF', label: 'Riboflavin', unit: 'mg', group: "vitamins"},
  {parameter: 'NA', label: 'Sodium', unit: 'mg', group: "minerals"},
  {parameter: 'Sugar.alcohol', label: 'Sugar alcohols', unit: 'g', group: "other"},
  {parameter: 'SUGAR.added', label: 'Sugar, added', unit: 'g', group: "macros"},
  {parameter: 'SUGAR', label: 'Sugar, total', unit: 'g', group: "macros"},
  {parameter: 'THIA', label: 'Thiamin (B1)', unit: 'mg', group: "vitamins"},
  {parameter: 'VITA_RAE', label: 'Vitamin A', unit: 'µg', group: "vitamins"},
  {parameter: 'VITB12', label: 'Vitamin B12', unit: 'µg', group: "vitamins"},
  {parameter: 'VITB6A', label: 'Vitamin B6', unit: 'mg', group: "vitamins"},
  {parameter: 'VITC', label: 'Vitamin C', unit: 'mg', group: "vitamins"},
  {parameter: 'VITD', label: 'Vitamin D', unit: 'µg', group: "vitamins"},
  {parameter: 'TOCPHA', label: 'Vitamin E', unit: 'mg', group: "vitamins"},
  {parameter: 'VITK1', label: 'Vitamin K', unit: 'µg', group: "vitamins"},
  {parameter: 'WATER', label: 'Water', unit: 'g', group: "other"},
  {parameter: 'ZN', label: 'Zinc', unit: 'mg', group: 'minerals'}
];

export const nutrientCodes: NutrientCode[] = [
  'CA',
  'CHOCDF.net',
  'CHOLE',
  'FAMS',
  'FAPU',
  'FASAT',
  'FAT',
  'FATRN',
  'FIBTG',
  'FOLDFE',
  //'FOLFE',
  'FOLAC',
  'FE',
  'MG',
  'NIA',
  'P',
  'K',
  'PROCNT',
  'RIBF',
  'NA',
  'Sugar.alcohol',
  'SUGAR.added',
  'SUGAR',
  'THIA',
  'VITA_RAE',
  'VITB12',
  'VITB6A',
  'VITC',
  'VITD',
  'TOCPHA',
  'VITK1',
  'WATER',
  'ZN'
];